
services:
  ibge-api:
    build: .
    container_name: projeto_ibge_api
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8001
